#!/bin/bash

# Run your script
ruby ./assets/mymaps_export.rb

# Exit with status code 0 to proceed with the commit, or non-zero to abort
if [ $? -ne 0 ]; then
  echo "The script failed. Commit aborted."
  exit 1
fi

# Allow the commit to proceed
exit 0
