source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "tzinfo-data"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-mentions", "~> 1.6.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-commonmark", "~> 1.3.1"
gem "jekyll-include-cache", "~> 0.2"
gem "jemoji", "~> 0.12"
gem "activesupport", "~> 7.0"
gem "jekyll-leaflet"
gem "webrick"